# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4a31ea69a25068a377be58c5750abc7da04870b4852ff522047b22dd06894d295db0094d20b7fa69c7413f7c916153349a6b26017465a88378cc363d742698

test:
  secret_key_base: 0df6a4184c5972934e46dc107e45fc005f9e8d54fb3432464b0b42d70c71486d56e6e9bc45b3be02c8287ac7cfa384cbfe4b72a2e97bebeb928b39a212229940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
